# Generated by Django 5.0.3 on 2024-03-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postvideo',
            name='video',
            field=models.FileField(upload_to='post-vidoe/'),
        ),
    ]
